import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";

const nunito = Nunito({
  variable: "--font-nunito", // Змінна для використання в CSS
  subsets: ["latin"],
  weight: ["400", "700"], // Додай необхідні товщини
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} antialiased`}>

        <Header/>
        {children}
      </body>
    </html>
  );
}
